# Generated by Django 5.1.3 on 2024-11-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ph', models.FloatField()),
                ('temperature', models.FloatField()),
                ('distance', models.IntegerField()),
            ],
        ),
    ]
