# Generated by Django 5.1.3 on 2024-11-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='arm_position',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='water_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
