# Generated by Django 5.1.3 on 2024-11-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensorreading_arm_position_sensorreading_water_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
