# Generated by Django 5.1.3 on 2024-11-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensorreading_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('measurement', 'Measurement'), ('water_drained', 'Water Drained'), ('water_filled', 'Water Filled')], max_length=20, null=True),
        ),
    ]
