# Generated by Django 3.2.25 on 2024-11-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_sensorreading_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('measurement', 'Measurement'), ('water_draining', 'Water Draining'), ('water_drained', 'Water Drained'), ('water_filling', 'Water Filling'), ('water_filled', 'Water Filled')], max_length=20, null=True),
        ),
    ]
